### ISSUE TITLE
Detector returning null when file is US-ASCII

### ISSUE THREAD

**Issue by guibernardi** [albfernandez/juniversalchardet#30]
Hi,

I have some files with us-ascii charset, for example on MacOs:

```
file -I file123.csv 
file123.csv: text/plain; charset=us-ascii
```
When I call the method for detect the charset I'm receiving a null:

`UniversalDetector.detectCharset(file.getInputStream());`

Is something that I'm doing wrong or the dependency doesn't support this charset?

Thanks!

**Comment by albfernandez** [comment]
I've released a new version that detect US-ASCII.
Hope it help you

**Comment by guibernardi** [comment]
It works, thank you!
