### ISSUE TITLE
Chinese Internal Code Specification (GBK) not supported?

### ISSUE THREAD

**Issue by liyujiang-gzu** [albfernandez/juniversalchardet#34]
After testing, GB2312 also can not be detected

**Comment by liyujiang-gzu** [comment]
After testing, GB2312 also can not be detected

**Comment by liyujiang-gzu** [comment]
By the way, use http://jchardet.sourceforge.net can detected

**Comment by siqiniao** [comment]
hope support , offcen use gbk ....

**Comment by albfernandez** [comment]
Hi
I don't know how to work (or test) with Chinesse Charsets. 
GB18030 was disabled in 2.0 to fix #9 and #11. 
Can you try version 1.0.3 and check if it  works for you. 
Then we can check to reenable.

**Comment by liyujiang-gzu** [comment]
> Hi
> I don't know how to work (or test) with Chinesse Charsets.
> GB18030 was disabled in 2.0 to fix #9 and #11.
> Can you try version 1.0.3 and check if it works for you.
> Then we can try to reenable.

Thank you for your reply.

**Comment by amake** [comment]
It's easy to create a file in GBK:

1. Copy some Chinese text from e.g. https://zh.wikipedia.org/wiki/%E6%B1%89%E5%AD%97%E5%86%85%E7%A0%81%E6%89%A9%E5%B1%95%E8%A7%84%E8%8C%83
2. Paste into an Emacs buffer visiting e.g. `~/gbk-sample.txt`
3. Do `M-x set-buffer-file-coding-system gbk` and save

The result is attached.
[gbk-sample.txt](https://github.com/albfernandez/juniversalchardet/files/5266613/gbk-sample.txt)

**Comment by liyujiang-gzu** [comment]
[gb2312-sample.txt](https://github.com/albfernandez/juniversalchardet/files/5266758/gb2312-sample.txt)

**Comment by amake** [comment]
I can confirm that juniversalchardet correctly detects the sample file after uncommenting the line [here](https://github.com/albfernandez/juniversalchardet/blob/a013857fb4b7faea7a509a6bf7819558f3280b8f/src/main/java/org/mozilla/universalchardet/prober/MBCSGroupProber.java#L65):

```
$ mvn test # fails because of false-positive unit tests
$ java -cp target/classes:target/test-classes org/mozilla/universalchardet/example/TestDetector gbk-sample.txt
Detected encoding = GB18030
```

I'm not sure what should be done to prevent the false positives. I checked and the texts in both of the unit tests don't seem to be valid GBK.

**Comment by liyujiang-gzu** [comment]
GB 18030 is compatible with GBK and GBK is compatible with GB2312.

**Comment by dwhmofly** [comment]
GB18030 is the registered Internet name for the official character set of the People's Republic of China (PRC) superseding GB2312.[1] As a Unicode Transformation Format[a] (i.e. an encoding of all Unicode code points), GB18030 supports both simplified and traditional Chinese characters. It is also compatible with legacy encodings including GB2312, CP936,[b] and GBK 1.0.

[https://en.wikipedia.org/wiki/GB_18030](https://en.wikipedia.org/wiki/GB_18030)

@amake Chinese just need GB18030
