### ISSUE TITLE
Migrate to JUnit 5

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/juniversalchardet#40]

**Comment by acuccovi** [comment]
Hi @albfernandez I'm trying to migrate to JUnit 5 and it works for almost all tests that are already present but not for 3 of them.
I've forked this repo and created a branch named it junit5.
If you can take a look and help me fixing them, they are:

- BasicStreamEncodingDetectionTest#testEUC
- BasicStreamEncodingDetectionTest#testWindows1255
- BasicStreamEncodingDetectionTest#testShiftJis

This is the url of the branch on my forked copy of this repo: [https://github.com/acuccovi/juniversalchardet/tree/junit5](https://github.com/acuccovi/juniversalchardet/tree/junit5)

**Comment by albfernandez** [comment]
Hi

You must close the detector streams before call getDetectedStream to tell
the detector de data is end.

Compare to the  current main version where close are called in the finally
block.

**Comment by acuccovi** [comment]
Cool!
Just created the [PR](https://github.com/albfernandez/juniversalchardet/pull/52)
