### ISSUE TITLE
Odd behavior of  universal detector in empty files.

### ISSUE THREAD

**Issue by blaze-centurion** [albfernandez/juniversalchardet#44]
```java
public boolean isBinaryFile(File file) {
    try {
        return UniversalDetector.detectCharset(file)==null;
    } catch (IOException e) {
        e.printStackTrace();
        return false;
    }
}
```

Here, this method is returning true when an empty text file is given.

**Comment by albfernandez** [comment]
Hi,

It's the default, return null when you cannot determine encoding. An empty file can be any encoding.

Do you have a suggestion for changing this default?

**Comment by blaze-centurion** [comment]
Ok and thank you for you response @albfernandez. 

But I am creating a text editor in which I want to run different code for binary file. But if user tried to open any empty file with the extension of .py, .java, .txt and etc. Then code which is running is for binary file. So please tell me how can I verify that whether the file is binary or not (in case of empty text file).
