### ISSUE TITLE
new 2.0.x release with bug fixes from 2.3.x and 2.4.0 backported

### ISSUE THREAD

**Issue by nift4** [albfernandez/juniversalchardet#55]
Hi, are you still maintaining android_4 branch? I'm interested in a new release with bug fixes backported. Thanks for this nice library :D

**Comment by albfernandez** [comment]
Hi

There are two new features since 2.0

- Detect US-ASCII
- Recovered support for GB-18030

Threre are no bugfixes on existing features in 2.0.x. There is no plan to backport the new features

**Comment by nift4** [comment]
Thanks for the reply, are you perhaps open on a pull request for backporting features?

**Comment by nift4** [comment]
https://github.com/albfernandez/juniversalchardet/pull/60

**Comment by albfernandez** [comment]
Released 2.0.4

**Comment by nift4** [comment]
Thank you
